In [6]:
from Scripts.generate_weight_from_json_netlist import generate_weights_from_json_netlist

h_total, J_total, nodes = generate_weights_from_json_netlist('../Yosys/Synthesized/AND_AND_OR_synthesized.json',SaveCircuit=True,CircuitName="AND_AND_OR")

Detected top module: AND_AND_OR
Overall bias vector (h_total) in np.array format:
np.array([-3., -3.,  1.,  1.,  1.,  1.,  2.])

Overall weight matrix (J_total) in np.array format:
np.array([[ 0., -2.,  0.,  2.,  0.,  2.,  3.],
 [-2.,  0.,  2.,  0.,  2.,  0.,  3.],
 [ 0.,  2.,  0.,  0., -1.,  0.,  0.],
 [ 2.,  0.,  0.,  0.,  0., -1.,  0.],
 [ 0.,  2., -1.,  0.,  0.,  0.,  0.],
 [ 2.,  0.,  0., -1.,  0.,  0.,  0.],
 [ 3.,  3.,  0.,  0.,  0.,  0.,  0.]])

Order of the matrix: 7 x 7

Node order (mapping of node names to indices):
["7", "8", "A10", "A20", "B10", "B20", "Y0"]
Saved weight data to C:\repositories\ProbabilisticComputing\Circuit_Library\AND_AND_OR.npz


In [7]:
import Scripts.CustomScripts as CS
J, h, node_order = CS.load_npz_data("AND_AND_OR.npz", target_folder="Circuit_Library")
CS.generate_mem_files(J, h, 'AND_AND_OR')

Found folder: C:\repositories\ProbabilisticComputing\Circuit_Library
[[ 0. -4.  0.  4.  0.  4.  6.]
 [-4.  0.  4.  0.  4.  0.  6.]
 [ 0.  4.  0.  0. -2.  0.  0.]
 [ 4.  0.  0.  0.  0. -2.  0.]
 [ 0.  4. -2.  0.  0.  0.  0.]
 [ 4.  0.  0. -2.  0.  0.  0.]
 [ 6.  6.  0.  0.  0.  0.  0.]]
[-8. -8.  0.  0.  0.  0. -4.]
11000000
11000000
00000000
00000000
00000000
00000000
11100000
Mem files generated in folder 'custom_hdl_files':
  AND_AND_OR_h.mem
  AND_AND_OR_J.mem
  AND_AND_OR_seeds.mem
Global parameters file generated: AND_AND_OR_global_params.sv
Lookup table file generated: grouped_update_order_LUT.sv
CSR_matrix mem files generated in folder 'custom_hdl_files\CSR_matrix':
  AND_AND_OR_values.mem
  AND_AND_OR_col_indices.mem
  AND_AND_OR_row_ptr.mem
  AND_AND_OR_h.mem
