In [1]:
import Scripts.CustomConversions as CC
import numpy as np

In [2]:
# Example usage
I = 4  # Number of integer bits
F = 3  # Number of fractional bits
min_val, max_val, step = CC.fixed_point_range_signed(I, F)

Fixed-Point Notation: s[4][3]
Minimum Value: -16
Maximum Value: 15.875
Step Size: 0.125


In [3]:
# Example usage
I = 0 # Number of integer bits
F = 32  # Number of fractional bits
min_val, max_val, step = CC.fixed_point_range_unsigned(I, F)

Fixed-Point Notation: s[0][32]
Minimum Value: 0
Maximum Value: 0.9999999997671694
Step Size: 2.3283064365386963e-10


In [4]:
# Weight matrix
J_bipolar = np.array([
    [0, -1, 2],
    [-1, 0, 2],
    [2, 2, 0]
])

# Bias 
h_bipolar_floating = np.array([1, 1, -2]) 
h_bipolar_AB = np.array([10, 10, -2]) 
h_bipolar_C = np.array([1, 1, -16]) 
J_binary_floating, h_binary_floating = CC.bipolar_to_binary(J_bipolar, h_bipolar_floating)
J_binary_AB, h_binary_AB = CC.bipolar_to_binary(J_bipolar, h_bipolar_AB)
J_binary_C, h_binary_C = CC.bipolar_to_binary(J_bipolar, h_bipolar_C)
print(f"J (floating) = \n{J_binary_floating}")
print(f"h (floating) = {h_binary_floating}")
print(f"h (AB) = {h_binary_AB}")
print(f"h (C) = {h_binary_C}")


J (floating) = 
[[ 0. -2.  4.]
 [-2.  0.  4.]
 [ 4.  4.  0.]]
h (floating) = [ 0.  0. -6.]
h (AB) = [ 9.  9. -6.]
h (C) = [  0.   0. -20.]


In [5]:
values = np.arange(-16,16, 0.125)
converted_values = [CC.decimal_to_s4_3(v) for v in values]

print(f"{'Decimal':>10} | {'Binary':>10} | {'Signed Int':>10}")
print("-" * 35)

for i, (binary, fixed_point) in enumerate(converted_values):
    print(f"{values[i]:10.3f} |{binary}| {fixed_point:10d}")


   Decimal |     Binary | Signed Int
-----------------------------------
   -16.000 |10000000|       -128
   -15.875 |10000001|       -127
   -15.750 |10000010|       -126
   -15.625 |10000011|       -125
   -15.500 |10000100|       -124
   -15.375 |10000101|       -123
   -15.250 |10000110|       -122
   -15.125 |10000111|       -121
   -15.000 |10001000|       -120
   -14.875 |10001001|       -119
   -14.750 |10001010|       -118
   -14.625 |10001011|       -117
   -14.500 |10001100|       -116
   -14.375 |10001101|       -115
   -14.250 |10001110|       -114
   -14.125 |10001111|       -113
   -14.000 |10010000|       -112
   -13.875 |10010001|       -111
   -13.750 |10010010|       -110
   -13.625 |10010011|       -109
   -13.500 |10010100|       -108
   -13.375 |10010101|       -107
   -13.250 |10010110|       -106
   -13.125 |10010111|       -105
   -13.000 |10011000|       -104
   -12.875 |10011001|       -103
   -12.750 |10011010|       -102
   -12.625 |10011011|       -101
   

In [6]:
CC.decimal_to_s4_3(-14)

('10010000', -112)

# Full Adder Weights

In [7]:
# Weight matrix
J_bipolar = np.array([
    [ 0, -1, -1,  1,  2],
    [-1,  0, -1,  1,  2],
    [-1, -1,  0,  1,  2],
    [ 1,  1,  1,  0, -2],
    [ 2,  2,  2, -2,  0]
])

# Bias 
h_bipolar_floating = np.array([0,0,0,0,0]) 


J_binary_floating, h_binary_floating = CC.bipolar_to_binary(J_bipolar, h_bipolar_floating)
J_binary_floating_formatted = ""
for i in range(J_binary_floating.shape[0]):
    for j in range(J_binary_floating.shape[1]):
        bin_value, _ = CC.decimal_to_s4_3(J_binary_floating[i, j])
        J_binary_floating_formatted += f"parameter J_{i}{j} = 8'sb{bin_value};\n"
h_binary_floating_formatted = ""
for i in range(h_binary_floating.shape[0]):
    bin_value, _ = CC.decimal_to_s4_3(h_binary_floating[i])
    h_binary_floating_formatted += f"h[{i}] = 8'sb{bin_value};\n"

print(f"J (floating) = \n{J_binary_floating}")
print(J_binary_floating_formatted)
print(f"h (floating) = {h_binary_floating}")
print(h_binary_floating_formatted)

J (floating) = 
[[ 0. -2. -2.  2.  4.]
 [-2.  0. -2.  2.  4.]
 [-2. -2.  0.  2.  4.]
 [ 2.  2.  2.  0. -4.]
 [ 4.  4.  4. -4.  0.]]
parameter J_00 = 8'sb00000000;
parameter J_01 = 8'sb11110000;
parameter J_02 = 8'sb11110000;
parameter J_03 = 8'sb00010000;
parameter J_04 = 8'sb00100000;
parameter J_10 = 8'sb11110000;
parameter J_11 = 8'sb00000000;
parameter J_12 = 8'sb11110000;
parameter J_13 = 8'sb00010000;
parameter J_14 = 8'sb00100000;
parameter J_20 = 8'sb11110000;
parameter J_21 = 8'sb11110000;
parameter J_22 = 8'sb00000000;
parameter J_23 = 8'sb00010000;
parameter J_24 = 8'sb00100000;
parameter J_30 = 8'sb00010000;
parameter J_31 = 8'sb00010000;
parameter J_32 = 8'sb00010000;
parameter J_33 = 8'sb00000000;
parameter J_34 = 8'sb11100000;
parameter J_40 = 8'sb00100000;
parameter J_41 = 8'sb00100000;
parameter J_42 = 8'sb00100000;
parameter J_43 = 8'sb11100000;
parameter J_44 = 8'sb00000000;

h (floating) = [-1. -1. -1. -1. -4.]
h[0] = 8'sb11111000;
h[1] = 8'sb11111000;
h[2] = 8'sb11

# AND-gate weights

In [10]:
J_bipolar = np.array([
    [0, -1, 2],
    [-1, 0, 2],
    [2, 2, 0]
])

h_bipolar = np.array([1, 1, -2])

J_params, J_init, h_params = CC.generate_verilog_params(J_bipolar, h_bipolar)

# Generate seeds
seeds_formatted = CC.generate_seed_array(len(h_bipolar))

# Print results
print("Generated Verilog Parameters:\n")
print(J_params)
print(J_init)
print()
print(h_params)
print("Generated Seeds:")
print(seeds_formatted)

Converted to binary:
[[ 0. -2.  4.]
 [-2.  0.  4.]
 [ 4.  4.  0.]]
[ 0.  0. -6.]
Generated Verilog Parameters:

parameter J_00 = 8'sb00000000;
parameter J_01 = 8'sb11110000;
parameter J_02 = 8'sb00100000;
parameter J_10 = 8'sb11110000;
parameter J_11 = 8'sb00000000;
parameter J_12 = 8'sb00100000;
parameter J_20 = 8'sb00100000;
parameter J_21 = 8'sb00100000;
parameter J_22 = 8'sb00000000;

logic signed [7:0] J [0:2][0:2] = '{{J_00, J_01, J_02},
{J_10, J_11, J_12},
{J_20, J_21, J_22}};

h[0] = 8'sb00000000;
h[1] = 8'sb00000000;
h[2] = 8'sb11010000;

Generated Seeds:
parameter seed0 = 32'b10110101111101001011101001111100;
parameter seed1 = 32'b11110100001101010000011000101101;
parameter seed2 = 32'b00101010010000111100011111110000;
logic [31:0] seed [0:2] = '{seed0, seed1, seed2};


# OR gate

In [11]:
# Weight matrix
J = np.array([
    [0, -2, 3],
    [-2, 0, 3],
    [3, 3, 0]
])

# Bias 
h = np.array([-1, -1, 2])  
J_params, J_init, h_params = CC.generate_verilog_params(J, h)

# Generate seeds
seeds_formatted = CC.generate_seed_array(len(h))

# Print results
print("Generated Verilog Parameters:\n")
print(J_params)
print(J_init)
print()
print(h_params)
print("Generated Seeds:")
print(seeds_formatted)

Converted to binary:
[[ 0. -4.  6.]
 [-4.  0.  6.]
 [ 6.  6.  0.]]
[-2. -2. -4.]
Generated Verilog Parameters:

parameter J_00 = 8'sb00000000;
parameter J_01 = 8'sb11100000;
parameter J_02 = 8'sb00110000;
parameter J_10 = 8'sb11100000;
parameter J_11 = 8'sb00000000;
parameter J_12 = 8'sb00110000;
parameter J_20 = 8'sb00110000;
parameter J_21 = 8'sb00110000;
parameter J_22 = 8'sb00000000;

logic signed [7:0] J [0:2][0:2] = '{{J_00, J_01, J_02},
{J_10, J_11, J_12},
{J_20, J_21, J_22}};

h[0] = 8'sb11110000;
h[1] = 8'sb11110000;
h[2] = 8'sb11100000;

Generated Seeds:
parameter seed0 = 32'b01000001111011100011010001000100;
parameter seed1 = 32'b01011010111101011101000001011110;
parameter seed2 = 32'b01010111000110010111000011010000;
logic [31:0] seed [0:2] = '{seed0, seed1, seed2};
