In [1]:
import Scripts.CustomConversions as CC
import numpy as np

# Notebooks for generating different parameters for the Full Adder

Truth table:
| A | B | C_in | Sum | C_out |
|:---:|:---:|:---:|:---:|:---:|
| 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 1 | 1 | 0 |
| 0 | 1 | 0 | 1 | 0 |
| 0 | 1 | 1 | 0 | 1 |
| 1 | 0 | 0 | 1 | 0 |
| 1 | 0 | 1 | 0 | 1 |
| 1 | 1 | 0 | 0 | 1 |
| 1 | 1 | 1 | 1 | 1 |

In [2]:
# Weight matrix
J_bipolar = np.array([
    [ 0, -1, -1,  1,  2],
    [-1,  0, -1,  1,  2],
    [-1, -1,  0,  1,  2],
    [ 1,  1,  1,  0, -2],
    [ 2,  2,  2, -2,  0]
])

# Bias 
h_bipolar_floating = np.array([0,0,0,0,0]) 

J_params, J_init, h_params = CC.generate_verilog_params(J_bipolar, h_bipolar_floating)

# Generate seeds
seeds_formatted = CC.generate_seed_array(len(h_bipolar_floating))

# Print results
print("Generated Verilog Parameters:\n")
print(J_params)
print(J_init)
print()
print(h_params)
print("Generated Seeds:")
print(seeds_formatted)

Converted to binary:
[[ 0. -2. -2.  2.  4.]
 [-2.  0. -2.  2.  4.]
 [-2. -2.  0.  2.  4.]
 [ 2.  2.  2.  0. -4.]
 [ 4.  4.  4. -4.  0.]]
[-1. -1. -1. -1. -4.]
Generated Verilog Parameters:

parameter J_00 = 8'sb00000000;
parameter J_01 = 8'sb11110000;
parameter J_02 = 8'sb11110000;
parameter J_03 = 8'sb00010000;
parameter J_04 = 8'sb00100000;
parameter J_10 = 8'sb11110000;
parameter J_11 = 8'sb00000000;
parameter J_12 = 8'sb11110000;
parameter J_13 = 8'sb00010000;
parameter J_14 = 8'sb00100000;
parameter J_20 = 8'sb11110000;
parameter J_21 = 8'sb11110000;
parameter J_22 = 8'sb00000000;
parameter J_23 = 8'sb00010000;
parameter J_24 = 8'sb00100000;
parameter J_30 = 8'sb00010000;
parameter J_31 = 8'sb00010000;
parameter J_32 = 8'sb00010000;
parameter J_33 = 8'sb00000000;
parameter J_34 = 8'sb11100000;
parameter J_40 = 8'sb00100000;
parameter J_41 = 8'sb00100000;
parameter J_42 = 8'sb00100000;
parameter J_43 = 8'sb11100000;
parameter J_44 = 8'sb00000000;

logic signed [7:0] J [0:4][0:4] = 

In [5]:
label_mapping = {
    (-1., -1., -1., -1., -4.): 'Floating State',
}

CC.generate_verilog_biases(label_mapping_binary=label_mapping)

#1000000;
// h_bipolar(Floating State)
h[0] = 8'sb11111000;
h[1] = 8'sb11111000;
h[2] = 8'sb11111000;
h[3] = 8'sb11111000;
h[4] = 8'sb11100000;
bias[0] = s4_3_to_real(h[0]);
bias[1] = s4_3_to_real(h[1]);
bias[2] = s4_3_to_real(h[2]);
bias[3] = s4_3_to_real(h[3]);
bias[4] = s4_3_to_real(h[4]);

