In [1]:
import Scripts.CustomScripts as CS
import numpy as np

# Notebooks for generating different parameters for the Full Adder

Truth table:
| A | B | C_in | Sum | C_out |
|:---:|:---:|:---:|:---:|:---:|
| 0 | 0 | 0 | 0 | 0 |
| 0 | 0 | 1 | 1 | 0 |
| 0 | 1 | 0 | 1 | 0 |
| 0 | 1 | 1 | 0 | 1 |
| 1 | 0 | 0 | 1 | 0 |
| 1 | 0 | 1 | 0 | 1 |
| 1 | 1 | 0 | 0 | 1 |
| 1 | 1 | 1 | 1 | 1 |

In [2]:
# Weight matrix
J_bipolar = np.array([
    [ 0, -1, -1,  1,  2],
    [-1,  0, -1,  1,  2],
    [-1, -1,  0,  1,  2],
    [ 1,  1,  1,  0, -2],
    [ 2,  2,  2, -2,  0]
])

# Bias 
h_bipolar_floating = np.array([0,0,0,0,0]) 

J_binary_formatted, J_array_init, h_binary_formatted, h_array_init = CS.generate_verilog_params(J_bipolar, h_bipolar_floating)

# Generate seeds
seeds_formatted = CS.generate_seed_array(len(h_bipolar_floating))

# Print results
print("Generated Verilog Parameters:\n")
print(J_binary_formatted)
print(J_array_init)
print()
print(h_binary_formatted)
print(h_array_init)
print("Generated Seeds:")
print(seeds_formatted)

Converted to binary:
[[ 0. -2. -2.  2.  4.]
 [-2.  0. -2.  2.  4.]
 [-2. -2.  0.  2.  4.]
 [ 2.  2.  2.  0. -4.]
 [ 4.  4.  4. -4.  0.]]
[-1.,-1.,-1.,-1.,-4.]
Generated Verilog Parameters:

parameter J_0000 = 8'sb00000000;
parameter J_0001 = 8'sb11110000;
parameter J_0002 = 8'sb11110000;
parameter J_0003 = 8'sb00010000;
parameter J_0004 = 8'sb00100000;
parameter J_0100 = 8'sb11110000;
parameter J_0101 = 8'sb00000000;
parameter J_0102 = 8'sb11110000;
parameter J_0103 = 8'sb00010000;
parameter J_0104 = 8'sb00100000;
parameter J_0200 = 8'sb11110000;
parameter J_0201 = 8'sb11110000;
parameter J_0202 = 8'sb00000000;
parameter J_0203 = 8'sb00010000;
parameter J_0204 = 8'sb00100000;
parameter J_0300 = 8'sb00010000;
parameter J_0301 = 8'sb00010000;
parameter J_0302 = 8'sb00010000;
parameter J_0303 = 8'sb00000000;
parameter J_0304 = 8'sb11100000;
parameter J_0400 = 8'sb00100000;
parameter J_0401 = 8'sb00100000;
parameter J_0402 = 8'sb00100000;
parameter J_0403 = 8'sb11100000;
parameter J_0404 =

In [3]:
label_mapping = {
    (-1., -1., -1., -1., -4.): 'Floating State',
}

CS.generate_verilog_biases(label_mapping_binary=label_mapping)

#1000000;
// h_bipolar(Floating State)
h[0] = 8'sb11111000;
h[1] = 8'sb11111000;
h[2] = 8'sb11111000;
h[3] = 8'sb11111000;
h[4] = 8'sb11100000;
bias[0] = s4_3_to_real(h[0]);
bias[1] = s4_3_to_real(h[1]);
bias[2] = s4_3_to_real(h[2]);
bias[3] = s4_3_to_real(h[3]);
bias[4] = s4_3_to_real(h[4]);

bias[0],
bias[1],
bias[2],
bias[3],
bias[4],


In [5]:
CS.generate_mem_files(J_bipolar, h_bipolar_floating, '5pbit_FA')

Mem files generated in folder 'bram':
  5pbit_FA_h.mem
  5pbit_FA_J.mem
  5pbit_FA_seeds.mem


In [ ]:
CS.generate_group_update_order(J_bipolar, var_names, group_bit_width=3)