# 8x8=8 - version

In [ ]:
from Scripts.CircuitSynth import CircuitSynth
CircuitSynth("Multiplier_8x8=8.v","8x8=8bIntFac")

# 8x8=16b

In [1]:
from Scripts.CircuitSynth import CircuitSynth
CircuitSynth("Multiplier_8x8=16.v","8x8=16bIntFac",write_coe=True)

Generated script: C:\repositories\ProbabilisticComputing\Yosys\scripts\Synth_Multiplier_8x8=16.ys

[OSS CAD Suite] C:\repositories\ProbabilisticComputing\Yosys>yosys -s scripts/Synth_Multiplier_8x8=16.ys

 /----------------------------------------------------------------------------\
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |  Copyright (C) 2012 - 2025  Claire Xenia Wolf <claire@yosyshq.com>         |
 |  Distributed under an ISC-like license, type "license" to see terms        |
 \----------------------------------------------------------------------------/
 Yosys 0.50+56 (git sha1 78960292d, x86_64-w64-mingw32-g++ 13.2.1 -O3)

-- Executing script file `scripts/Synth_Multiplier_8x8=16.ys' --

1. Executing Verilog-2005 frontend: C:\repositories\ProbabilisticComputing\Yosys\Sources\Multiplier_8x8=16.v
Parsing Verilog input from `C:\repositories\ProbabilisticComputing\Yosys\Sources\Multiplier_8x8=16.v' to AST representation.
Generating RTLIL repres

In [ ]:
from scipy.sparse import csr_matrix
import matplotlib.pyplot as plt
from Scripts.CustomScripts import load_npz_data
J, h, node_order = load_npz_data("8x8=16bIntFac.npz")
# Convert J to Compressed Sparse Row (CSR) format
J_sparse = csr_matrix(J)

# Extract CSR components
values = J_sparse.data
col_indices = J_sparse.indices
row_ptr = J_sparse.indptr

# Calculate number of non-zero elements per row
nonzeros_per_row = J_sparse.indptr[1:] - J_sparse.indptr[:-1]

# Count how many rows have each possible number of non-zeros
unique, counts = np.unique(nonzeros_per_row, return_counts=True)

# Plot histogram
plt.figure(figsize=(8, 4))
plt.bar(unique, counts)
plt.title("Distribution of Non-Zero Values per Row (8x8=16b - 459 P-bits)")
plt.xlabel("Number of Non-Zero Values in a Row")
plt.ylabel("Number of Rows")
plt.grid(True, axis='y')
plt.tight_layout()
plt.show()

Found folder: C:\repositories\ProbabilisticComputing\Circuit_Library
[[ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0. -1. ...  0.  0.  0.]
 [ 0. -1.  0. ...  0.  0.  0.]
 ...
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]
 [ 0.  0.  0. ...  0.  0.  0.]]
[ 3.  4.  3.  2.  2.  3.  4.  2.  3.  4.  2.  2. -2.  2.  4.  3.  2.  3.
  4.  2.  3.  4.  2.  3.  4.  2.  3.  4.  0.  2.  2.  2. -2.  2.  3.  3.
  2. -2.  2.  2. -2.  4.  3.  2.  3.  4.  2. -2.  2.  2.  3.  0.  4.  4.
  2.  3.  4.  2.  3.  4.  2.  3.  4.  2.  3.  4.  2.  3.  4. -2.  3.  3.
  2.  4.  3.  2.  4.  3. -2. -2.  2.  2. -2.  3.  4.  2.  3.  4.  2. -2.
  2. -2. -2.  4.  3.  2.  3.  4.  2. -2.  2.  3.  3.  2.  4.  2.  3.  4.
  2.  3.  4.  2.  3.  4.  2.  3.  4.  2.  3.  4.  2.  3.  4.  2.  4.  3.
  2.  4.  3.  2.  3.  4.  2.  2. -2. -2. -2.  2.  4.  3. -2.  4.  3.  2.
 -2.  2. -1.  3.  4.  3.  2.  3.  4.  2. -2.  3.  0.  4.  3.  2.  3.  4.
  2.  3.  4.  2.  3.  4.  2.  3.  4.  2.  3.  4. -2.  4.  3. -2.  4.  3.
 -2.  2. 

NameError: name 'np' is not defined